name: fun_education_app_teacher
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  board_datetime_picker: ^2.0.0
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.4
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  image_gallery_saver: ^2.0.3
  image_picker: ^1.1.2
  intl: ^0.19.0
  overlap_stack: ^1.0.1
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
