name: fun_education_app_teacher
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  board_datetime_picker: ^2.0.0
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  file_picker: ^5.2.2
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.4
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_cached_pdfview: ^0.4.2
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^17.2.2
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  image_gallery_saver: ^2.0.3
  image_picker: ^1.1.2
  intl: ^0.19.0
  loading_animation_widget: ^1.2.1
  overlap_stack: ^1.0.1
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icApplicationLogo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
